input {
  file {
    path => "/logs/backend/backend.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
    add_field => { "service" => "microcrm-back" }
  }

  file {
    path => "/logs/frontend/frontend.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
    add_field => { "service" => "microcrm-front" }
  }
}

filter {
  if [level] {
    mutate { uppercase => ["level"] }
  }
}

output {
  elasticsearch { hosts => ["http://elasticsearch:9200"] index => "microcrm-logs-%{+YYYY.MM.dd}" }
}
