name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

permissions:
  contents: read

jobs:
  backend:
    name: Build & Test (Back-end)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      checks: write
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Build & Test
        uses: ./.github/actions/ci-backend

  frontend:
    name: Build & Test (Front-end)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      checks: write
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Build & Test
        uses: ./.github/actions/ci-frontend

  sonarqube:
    name: Analyse Qualite / Securite (SonarQube)
    runs-on: ubuntu-latest
    needs:
      - backend
      - frontend
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    timeout-minutes: 20
    permissions:
      contents: read

    steps:
      - name: Analyse Qualite / Securite (SonarQube)
        uses: ./.github/actions/ci-sonarqube
